[project]
name = "dungeonbuilder"
version = "1.0.0"
description = "Dunegon builder engine"
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"